### ISSUE TITLE
yt-dlp requested format is no longer available

### ISSUE THREAD

**Issue by A765-ALEX** [CC-YouCube/server#16]
### Description

yt-dlp doesnt seem to be working.

### Reproduction steps

1. enter a video (url or search, doesnt matter) on youtube (in this case [this video](https://www.youtube.com/watch?v=OwEVFQLPPbE))
2. won't download video at all, errors out

### Screenshots

![computer monitor](https://github.com/CC-YouCube/server/assets/67318684/f728364b-7351-497b-91fc-c59105035a50)

### Logs

```bash
[20:52:56 INFO] [YouCube] [127.0.0.1] Connected!
[20:52:56 DEBUG] [YouCube] [127.0.0.1] My headers are: <Header('user-agent': 'computercraft/1.101.4', 'host': '127.0.0.1:5000', 'upgrade': 'websocket', 'connection': 'upgrade', 'sec-websocket-key': 'MjTQoaGvVu6kWXO/g/y5yA==', 'sec-websocket-version': '13', 'sec-websocket-extensions': 'permessage-deflate;client_no_context_takeover;client_max_window_bits,deflate-frame,x-webkit-deflate-frame')>
[20:52:57 DEBUG] [YouCube] [127.0.0.1] Message: {"action":"handshake"}
[20:53:07 DEBUG] [YouCube] [127.0.0.1] Message: {"height":99,"url":"https://www.youtube.com/watch?v=OwEVFQLPPbE","action":"request_media","width":164}
[20:53:07 DEBUG] [YouCube] [yt-dlp] [youtube] Extracting URL: https://www.youtube.com/watch?v=OwEVFQLPPbE
[20:53:07 DEBUG] [YouCube] [yt-dlp] [youtube] OwEVFQLPPbE: Downloading webpage
[20:53:07 DEBUG] [YouCube] [yt-dlp] [youtube] OwEVFQLPPbE: Downloading ios player API JSON
[20:53:08 DEBUG] [YouCube] [yt-dlp] [youtube] OwEVFQLPPbE: Downloading player 9ed4a7e1
[20:53:08 WARNING] [YouCube] [yt-dlp] [youtube] OwEVFQLPPbE: nsig extraction failed: Some formats may be missing
         n = C5LUjY0PtkE3DCKp ; player = https://www.youtube.com/s/player/9ed4a7e1/player_ias.vflset/en_US/base.js
[20:53:08 WARNING] [YouCube] [yt-dlp] [youtube] OwEVFQLPPbE: nsig extraction failed: Some formats may be missing
         n = i6wDZqKf7fHF01FM ; player = https://www.youtube.com/s/player/9ed4a7e1/player_ias.vflset/en_US/base.js
[20:53:08 DEBUG] [YouCube] [yt-dlp] [youtube] OwEVFQLPPbE: Downloading m3u8 information
[20:53:08 ERROR] [YouCube] [yt-dlp] ERROR: [youtube] OwEVFQLPPbE: Requested format is not available. Use --list-formats for a list of available formats
Exception in thread Thread-1 (run_with_thread_save_asyncio_event_with_return_value):
Traceback (most recent call last):
  File "/home/aleksa/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1622, in wrapper
    return func(self, *args, **kwargs)
  File "/home/aleksa/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1778, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/aleksa/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1837, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/home/aleksa/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2974, in process_video_result
    raise ExtractorError(
yt_dlp.utils.ExtractorError: [youtube] OwEVFQLPPbE: Requested format is not available. Use --list-formats for a list of available formats

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aleksa/server/src/youcube/yc_magic.py", line 42, in run_with_thread_save_asyncio_event_with_return_value
    result = func(*args)
  File "/home/aleksa/server/src/youcube/yc_download.py", line 216, in download
    data = yt_dl.extract_info(url, download=False)
  File "/home/aleksa/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1611, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/home/aleksa/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1640, in wrapper
    self.report_error(str(e), e.format_traceback())
  File "/home/aleksa/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1088, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "/home/aleksa/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1027, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: [youtube] OwEVFQLPPbE: Requested format is not available. Use --list-formats for a list of available formats
```

**Comment by A765-ALEX** [comment]
i have tried reinstalling yt-dlp and all its deps

also tried other videos

**Comment by TheHomecraft** [comment]
I have an issue similar to yours. When I try to watch a video, youtube-dlp throws this error:
`yt_dlp.utils.DownloadError: ERROR: unable to download video data: HTTP Error 403: Forbidden`
I think it's an issue with the YouTube servers which are blocking downloaders like yt-dl.

**Comment by CanadianBaconBoi** [comment]
Issue has been fixed in yt-dlp in latest nightly build.

See yt-dlp/yt-dlp#10396 and yt-dlp/yt-dlp#10401.

**Comment by CanadianBaconBoi** [comment]
Issue has been fixed in yt-dlp in latest nightly build.

Downloadable here: https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/tag/2024.07.10.232707

See yt-dlp/yt-dlp#10396 and yt-dlp/yt-dlp#10401 for change info.

**Comment by A765-ALEX** [comment]
alright, thanks, ill close this
